version: '3'
services:
  jenkins:
    build: 
      dockerfile: JenkinsDockerfile
      context: .
    environment: 
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false -Dpermissive-script-security.enabled=true
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jcasc.yaml
    networks:
      - sonarnet
    ports:
      - "8080:8080"
    volumes:
       - jenkins_data:/var/jenkins_home
  nexus-3:
    image: "sonatype/nexus3:3.42.0"
    networks:
      - sonarnet
    ports:
        - "8081:8081"
networks:
  sonarnet:
    driver: bridge

volumes:
  jenkins_data:
